[package]
name = "test-proc-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = "2"
quote = "1"

server = { path = "../server", optional = true }

[features]
username = ["dep:server"]
password = ["dep:server"]
email = ["dep:server"]

[dev-dependencies]
syn = { version = "2", features = ["extra-traits"] }
