[package]
name = "data-access"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8", features = ["sqlite"] }

cache = { path = "../cache" }

[features]
tracing = ["cache/tracing"]
