[package]
name = "data-access"
edition = "2024"

[dependencies]
sqlx = { version = "0.8", features = ["sqlite", "time"] }
thiserror = "2"

cache = { path = "../cache" }

[features]
tracing = ["cache/tracing"]
