[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
axum = "0.7"
axum-extra = { version = "0.9", features = ["cookie"] }
axum-macros = "0.4"
bcrypt = "0.15"
dotenv = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8", features = [
    "migrate",
    "runtime-tokio-native-tls",
    "sqlite",
    "time",
] }
thiserror = "1"
time = "0.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.6", features = ["cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3" }
uuid = { version = "1.2", features = ["v4"] }

[build-dependencies]
dotenv = "0.15"
sqlx = { version = "0.8", features = [
    "sqlite",
    "runtime-tokio-native-tls",
    "migrate",
] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
