[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
axum-extra = { version = "0.10", features = ["cookie"] }
axum-macros = "0.5"
bcrypt = "0.17"
clap = { version = "4", optional = true }
# lettre = { version = "0.11", features = ["smtp-transport", "serde"] }
dashmap = "6.1"
forwarded-header-value = "0.1.1"
http = "1"
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-rustls", "sqlite"] }
sysinfo = { version = "0.35", features = ["serde"] }
thiserror = "2"
time = "0.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["fs", "request-id", "trace"] }
tracing = "0.1"
tracing-subscriber = "0.3"

auth = { path = "../auth", features = ["axum", "tracing"] }
boxer = { path = "../boxer" }
dashcache = { path = "../dashcache", features = ["tracing"] }
data-access = { path = "../data-access", features = ["tracing"] }
email = { path = "../email", features = ["sqlite"] }
extra = { path = "../extra", features = ["json-error-response"] }
tag = { path = "../tag" }
validation = { path = "../validation" }

[dev-dependencies]
test-proc-macros = { path = "../test-proc-macros", features = [
    "email",
    "password",
    "username",
] }
# lettre = { version = "0.11", features = ["file-transport"] }

[features]
cli = ["dep:clap", "clap/derive"]
email = []
env = []
ui = []

default = ["env"]
