[package]
name = "oblivious"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22"
clap = { version = "4", features = ["derive", "env"] }
jose-jwk = "0.1"
serde_json = "1"
sha2 = "0.10"
thiserror = "2.0.17"
